Azure/Enterprise-Scale

- docs/reference/contoso/armTemplates/auxiliary/diagnosticsAndSecurity.json
- docs/reference/contoso/armTemplates/auxiliary/logAnalytics.json
- docs/reference/contoso/armTemplates/auxiliary/lz.json
- docs/reference/contoso/armTemplates/auxiliary/policies.json
- docs/reference/contoso/armTemplates/auxiliary/vwan-connectivity.json
- docs/reference/contoso/armTemplates/es-vwan.json
- docs/reference/contoso/armTemplates/portal-es-vwan.json
> vwan-refresh

- .azure-pipelines/azops-pull.yml
Scheduled jobs were being skipped as the condition wasn't being met.
Added an additional build reason to account for 'Schedule' trigger type.
> Fix schedule trigger

- docs/Deploy/getting-started.md
Minor update to getting started to ensure Windows users have long filename support configured before using git clone.
> Update getting-started.md to put long filename instructions earlier 

- docs/Deploy/getting-started.md
At the end of the prerequires we should go back to the introduction or deploy a tenant vs jumping to the github setup the second phase of ES in-a-box. Feedback from proctors running through the workshop. 
> Process organization

- .azure-pipelines/azops-pull.yml
- .azure-pipelines/azops-push.yml
Discovery happends depending an access permission.
> Remove discovery root environment variable from ADO pipeline

- docs/reference/lzs/armTemplates/eslz.json
- docs/reference/lzs/armTemplates/portal-eslz.json
* Enables creation of new landing zones (subscriptions) using ARM template and portal
* Supports creation of multiple subscriptions
* Subscription can target specific management group(s)
> file-new-lz

- docs/EnterpriseScale-Deploy-landing-zones.md
- docs/reference/lzs/armTemplates/eslz.json
* Invokes the deployment at management group scope, and will use "scope" property to route the subscription creation request to the tenant root (/).
* Does no longer require permissions at the tenant root scope for creating subscriptions
> adding scope-escape to LZ create experience

- docs/EnterpriseScale-Setup-azure.md
advanced user probably don't think about it, but as i was going through documentation I found reference only to powershell modules Az.Resource and Az.Accounts. No details how to sign in/authenticate/select subscription. I think it should be referenced in some pages. 
Added info about following commandlets Connect-AzAccount, Get-AzSubscription, Select-AzSubscription
> add information about authentication in to azure subscription

- docs/Deploy/enable-subscription-creation.md
Replaced code to retrieve Access Token with Get-AzAccessToken cmdlet and replaced code that used that Token variable.
The documentation does not use the (new) Get-AzAccessToken cmdlet. e.g. https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/enable-subscription-creation.md
```PowerShell
$azureRmProfile = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile
$profileClient = [Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient]::new($azureRmProfile)
$token = $profileClient.AcquireAccessToken($currentContext.Tenant.Id)
```
Should be changed to:
```PowerShell
$Token = Get-AzAccessToken
```
[Link to issue](https://github.com/Azure/Enterprise-Scale/issues/395)
> Used Get-AzAccessToken cmdlet

- docs/reference/adventureworks/armTemplates/auxiliary/hubspoke-connectivity.json
- docs/reference/adventureworks/armTemplates/es-hubspoke.json
- docs/reference/adventureworks/armTemplates/portal-es-hubspoke.json
* Support for Availability Zones for networking components
* Dynamically list AZ depending on initial region selected
* Dynamically assign the right sku's for NW components
> Adventure Works: adding support for Availability Zones for connectivity

- docs/reference/adventureworks/armTemplates/auxiliary/policies.json
- docs/reference/contoso/armTemplates/auxiliary/policies.json
- docs/reference/treyresearch/armTemplates/auxiliary/policies.json
- docs/reference/wingtip/armTemplates/auxiliary/policies.json
This PR updates a missing fix for character casing where `"type": "string"` should be `"type": "String"`
> Fix character casing for "type": "String"

- docs/reference/adventureworks/armTemplates/auxiliary/policies.json
- docs/reference/contoso/armTemplates/auxiliary/policies.json
- docs/reference/treyresearch/armTemplates/auxiliary/policies.json
- docs/reference/wingtip/armTemplates/auxiliary/policies.json
This PR updates the policy name for `Deploy-Diagnostics-DataExplorerCluster` to ensure correct use of `PascalCasing`.
It also udpates the reference to Policy Definition `Deploy-PostgreSQL-sslEnforcement` in Policy Set Definition `Deploy-Diag-LogAnalytics` to match the casing used in the Policy Definition.
These changes, whilst cosmetic in ARM, are necessary to ensure consistent processing in the [Terraform Module for Cloud Adoption Framework Enterprise-scale](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale) and were highlighted as part of the latest [Update Library Templates](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/66) action.
> Consistent Policy Name Casing

- docs/reference/adventureworks/README.md
- docs/reference/contoso/Readme.md
- docs/reference/treyresearch/README.md
- docs/reference/wingtip/README.md
1. Remark out the whole  Enterprise-Scale Management Group Structure section, as it's already described [here](https://github.com/Azure/Enterprise-Scale/wiki/How-Enterprise-Scale-Works#enterprise-scale-management-group-structure).
2. Change section headline ## What happens when you deploy Enterprise-Scale? to ## What will be deployed? to conform to AdventureWorks and Trey Research readmes.
3. Remove whole Deployment section as it's outdated and is better described [here](https://github.com/Azure/Enterprise-Scale/wiki/Deploying-Enterprise-Scale).
> Update wingtipreadme to conform to other readmes

- docs/reference/adventureworks/armTemplates/auxiliary/policies.json
- docs/reference/contoso/armTemplates/auxiliary/policies.json
- docs/reference/treyresearch/armTemplates/auxiliary/policies.json
- docs/reference/wingtip/armTemplates/auxiliary/policies.json
I could not get the policy Append-AppService-latestTLS to have any effect. I got help from Johan Dahlbom and it turned out that mode needs to be set to All for this one. I have tested on local version and with this fix the policy works.
> Update policy mode Indexed->All for TLS version

- docs/wiki/Whats-new.md
- eslzArm/eslz-portal.json
In the UI experience for the reference implementation subscription with state != Enabled are excluded.
1. Excludes Subscriptions (state != Enabled from LZ filter for connected and online LZ
Testing has been performed in my own tenant with 3 subscriptions one of them "disabled".
> Update filter for "disabled" subscription state

- docs/wiki/Whats-new.md
Adds September 2021 to the Wiki "What's New?" TOC and fixes the AzOps version number typo
1. Adds September 2021 to the Wiki "What's New?" TOC and fixes the AzOps version number typo (V1.4.0 instead of V1.5.0)
None
This is a Wiki page change which is valid markdown and can be tested by visiting it in the branch here: https://github.com/Azure/Enterprise-Scale/blob/jtracey93-patch-1/docs/wiki/Whats-new.md#september-2021
> Add September to TOC and typo for AzOps version number

- docs/Deploy/deploy-lz-vnet.md
**Overview/Summary**
This pull request addresses the issue described in #856
This PR fixes/adds/changes/removes
- Change path to template containing Deploy-VNET-HubSpoke policy from https://github.com/Azure/Enterprise-Scale/blob/main/azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ%20(ESLZ)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-VNET-HubSpoke.parameters.json to https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/managementGroupTemplates/policyDefinitions/policies.json
- Change wording to specify that there is only one policy and it only deploys  a vnet and peering in a hub/spoke scenario. No support for Virtual WAN virtual network connections is provided. 
N/A
Not required since this is all documentation.
> Change wording and link

- docs/wiki/Whats-new.md
- eslzArm/README-AzureChina.md
- eslzArm/managementGroupTemplates/policyAssignments/china/mcDINE-ASCConfigPolicyAssignment.json
- eslzArm/managementGroupTemplates/policyDefinitions/china/mcPolicies.json
1. Tracked in issue #867  
1. Updated [DIY instructions](https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/README-AzureChina.md) for deploying Enterprise-Scale in Azure China with:
- Additional details of some deployment steps
- Microsoft Defender for Cloud configuration policy set definition and policy assignment specific to Azure China
- Differentiate between Az Vm Backup policy assignment for identity management group, and landing zone management group in the DIY guidance
2. The following policy definitions for Microsoft Defender for Cloud configurations are not available as built-in in Azure China. The policy set definition will be updated as when these policy definitions are available:
- defenderForOssDb, defenderForSqlServerVirtualMachines, defenderForAppServices, …
> Mooncake updates

- .github/CODEOWNERS
The current CODEOWNERS has not been working as expected.
Fixing casing on CODEOWNERS file for same teams as already defined to match their representation in GitHub Teams. As per docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax
Group names shown below in lowercase:
1. Fixing casing on CODEOWNERS file for same teams as already defined to match their representation in GitHub Teams
None
Not possible
> Fix casing on CODEOWNERS teams

- docs/wiki/Whats-new.md
- eslzArm/eslzArm.json
- eslzArm/subscriptionTemplates/vwan-connectivity.json
Currently, only the Hub & Spoke implementation includes a Firewall Policy for the Azure Firewall deployment.
This PR adds creation of a Firewall Policy and associates it with the Azure Firewall deployed to a Virtual Hub.
I have used all existing input parameters, so no changes should be needed in the Portal experience.
1. Add a `Microsoft.Network/firewallPolicies` resource and link it to the `Microsoft.Network/azureFirewalls` resource in the `eslzArm/subscriptionTemplates/vwan-connectivity.json` deployment template.
2. Add this update to the `docs/wiki/Whats-new.md` page.
none
> **NOTE**: I do not believe there are any Wiki docs which need updating with this change (other than the What's new page) but please let me know if this would be useful to add somewhere.
> Add Firewall Policy resource for VWAN implementation

- .github/fabricbot.json
Adds the `fabricbot.json` config file from the FabricBot config portal to the correct location of `.github/`
1. Fixes #933 
**None**
This has been done in the ALZ-Bicep repo successfully. https://github.com/Azure/ALZ-Bicep/blob/main/.github/fabricbot.json
> Add FabricBot Config-as-Code

- docs/EnterpriseScale-Setup-azure.md
Added `--output tsv` to the embedded `az ad signed-in-user show` command.
> Make root Owner assignment in Bash more robust

- docs/wiki/Whats-new.md
- eslzArm/eslzArm.json
This PR improves deployment name uniqueness, as per #1077, and fixes vNet naming for ALZ Portal Accelerator, as per #881.
1. Fixes #1077 - FYI @JefferyMitchell 
2. Fixes #881 
vNet naming pattern changed:
- **From:**
- Identity vNet: `<Subscription ID>-<Root ID Prefix>-vnet-<Region Short Name>`
- Corp vNets: `<Subscription ID>-<Root ID Prefix>-vnet-<Region Short Name>`
- **To:**
- Identity vNet: `<Root ID Prefix>-vnet-<Region Short Name>-<Subscription ID>` (then trimmed to 64 characters, using `take()` function, starting at front - so Subscription ID will get trimmed)
- Corp vNets: `<Root ID Prefix>-vnet-<Region Short Name>-<Subscription ID>` (then trimmed to 64 characters, using `take()` function, starting at front - so Subscription ID will get trimmed)
- **⚠️This is a breaking change, …
> Improve deployment name uniqueness and fix vNet naming for ALZ Portal Accelerator

- .github/workflows/test-portal.yml
- .github/workflows/update-portal.yml
- .github/workflows/wiki-sync.yml
- eslzArm/managementGroupTemplates/policyDefinitions/policies.json
1. Fix set-output deprecation as documented in [GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
2. Update triggers to improve workflow behaviour
3. Fixes the issue observed in PR #1059 
none
n/a
> Update workflows to fix permissions error

- src/Alz.Tools/functions/Alz.Tools.ps1
Fix multiline input for `Edit-LineEndings` function
1. Fix `Edit-LineEndings` function to ensure correct handling of `[string[]]` input
n/a
n/a
> Fix multiline input for `Edit-LineEndings` function

- docs/wiki/ALZ-Deprecated-Services.md
- docs/wiki/Whats-new.md
- eslzArm/managementGroupTemplates/policyDefinitions/policies.json
As well as policy IDs that supersede the ALZ Custom policies, there is now a link to AzAdvertizer of the superseded policy. 
1. Adds links to the superseded policies
1. N/A
N/A
[![Deploy To Azure](https://docs.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FJamJarchitect%2FEnterprise-Scale%2Flinkstopolicies%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FJamJarchitect%2FEnterprise-Scale%2Flinkstopolicies%2FeslzArm%2Feslz-portal.json)
[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazuregov.svg?sanitize=true)](https://portal.azure …
> US 24400 - Links to superseded policies

- docs/wiki/Deploying-ALZ-Pre-requisites.md
The previous code example does not work if you use
- External accounts (f.eg GitHub login)
- Cloud Shell (Context account is `MSI@nnnn`, not your identity)
Using `Get-AzAduser -SignedIn` works in most cases as it uses the /me endpoint to get connected user.
> Use -SignedIn to get current user

- docs/wiki/ALZ-Contribution-Guide.md
Updated Contribution Guidance for policy contribution naming convention.
AB #23845
1. Updates the Contribution Guidance for policy naming convention
1. N/A
N/A
[![Deploy To Azure](https://docs.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FJamJarchitect%2FEnterprise-Scale%2Fpolicycontributionguidance%2FeslzArm%2FeslzArm.json/uiFormDefini …
> ALZ Contribution Guide - Policy Naming Convention

- docs/wiki/Update-ALZ-Custom-Policies-to-Latest.md
Some bug fix for the code example in the **Update ALZ Custom Policies to Latest** WIKI article.
1. For the last code example in the Wiki article, uses the correct POSH parameter name, $policySetDefinitionLocation
N/A
Validated code by running it in my lab to update Deploy-MDFC-Config policy initiative.
N/A
> fix: Update MG location parameter name

- eslzArm/eslz-portal.json
Portal Accelerator Bug Bix - moving components arounds in the portal accelerator "Landing zones configuration" tab, missed adjusting sub-parameters when networking components configured - specifically being able to specify network segments. This PR fixes that experience.
1. `eslz-portal.json`
1. N/A
N/A
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#view/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain-fix-sachana%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain-fix-sachana%2FeslzArm%2Feslz-portal.json)
> Portal Accelerator Bug Bix

- eslzArm/managementGroupTemplates/policyAssignments/DINE-PrivateDNSZonesPolicyAssignment.json
The casing of the parameter was causing an idempotency issue in the downstream Terraform module, which is case sensitive.
will eventually fix Azure/terraform-azurerm-caf-enterprise-scale#699
None
N/A
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fjaredfholgate%2FEnterprise-Scale%2Fbug-fix-policy-assignment-parameter-casing%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fjaredfholgate%2FEnterprise-Scale%2Fbug-fix-policy-assignment-parameter-casing%2FeslzArm%2Feslz-portal.json)
[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTR …
> Bug - Fix case for azureIotPrivateDnsZoneId parameter in policy assignment

- docs/wiki/ALZ-Setup-azure.md
- docs/wiki/Whats-new.md
The Azure CLI command that assigns _Owner_ role on the Tenant root to the Service Principal is not working.
Fix the command to assign Owner role to the Service Principal.
None
> Fix: Wiki ALZ Azure Setup Bash command

- docs/wiki/Whats-new.md
- eslzArm/eslzArm.json
Fixed a bug in the portal accelerator experience when deploying with single platform subscription and selecting virtual WAN networking topology - Invalid Template error. Added missing parameters for recently introduced vWAN Hub features into ES Lite Only deployment for vWAN.
GitHub Issue: Bug Report Deployment template validation fails when selecting Virtual WAN and single subscription #1470
1. Updated `eslzArm.json`
1. N/A
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#view/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Frozkurt%2FEnterprise-Scale-rozkurt%2FvWAN_with_Single_Subscription_Deployment_Bug_Fix%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fra …
> vWAN with single subscription deployment bug fix

- docs/wiki/Whats-new.md
- eslzArm/eslz-portal.json
- eslzArm/eslzArm.json
- eslzArm/managementGroupTemplates/policyAssignments/DINE-MDFCConfigPolicyAssignment.json
Updating Portal Accelerator MDFC VM Vulnerability Assessment to use mdeTVM by default
1. Changed the recommended default to Microsoft Defender vulnerability management:
1. N/A
As above
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#view/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FSpringstone%2FEnterprise-Scale%2F31505%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FSpringstone%2FEnterprise-Scale%2F31505%2FeslzArm%2Feslz-portal.json)
> Updating Portal Accelerator MDFC VM Vulnerability Assessment to use mdeTVM by default

- utils/github/alz-repo-standard-labels.csv
This pull request adds new labels to the `alz-repo-standard-labels.csv` file in the `utils/github` directory. These labels are used to categorize and track issues and pull requests in ALZ repositories.
* <a href="diffhunk://#diff-bc50e7a613afd406eb9d34c3af0781800eb59de786b75b53f223307aec0262e2R1-R51">`utils/github/alz-repo-standard-labels.csv`</a>: Added new labels to categorize and track issues and pull requests.
> Add CSV for ALZ Standard Repo Labels

- docs/wiki/Whats-new.md
- eslzArm/eslz-portal.json
Add `userAssignedIdentityResourceGroup` as output for the Portal UI
1. #1565
N/A
N/A
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FSvenAelterman%2FEnterprise-Scale%2FSvenAelterman-patch-1%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FSvenAelterman%2FEnterprise-Scale%2FSvenAelterman-patch-1%2FeslzArm%2Feslz-portal.json)
[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazuregov.svg?sanitize=true)](https://portal.azure.us/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2F …
> Fix for #1565: pass `userAssignedIdentityResourceGroup` to deployment

- docs/wiki/Whats-new.md
- eslzArm/eslzArm.json
Parameter `corpConnectedLzSubscriptionId ` receives an object from the portal output. This object contains both subscription IDs and address spaces. This caused an issue in `subscriptionIds ` (array of subscriptions IDs.)
Now uses lambda function to obtain the subscription IDs from `corpConnectedLzSubscriptionId`. This fixes Invalid Template error when selecting a corp connected landing zone deployment.
1. Fixes #1570 
None
Tested:
- Hub and spoke - corp not connected
- Hub and spoke - corp connected
- Hub and spoke - online
- Virtual WAN 
Deployment:
The below URLs can be updated where the placeholders are, look for `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}` & `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}`, to allow you to test your portal deployment …
> Fixes 1570 portal deployment issue

- docs/wiki/Whats-new.md
- eslzArm/eslzArm.json
- eslzArm/managementGroupTemplates/policyAssignments/DINE-ChangeTrackingVMArcPolicyAssignment.json
- eslzArm/managementGroupTemplates/policyAssignments/DINE-ChangeTrackingVMPolicyAssignment.json
- eslzArm/managementGroupTemplates/policyAssignments/DINE-ChangeTrackingVMSSPolicyAssignment.json
- eslzArm/managementGroupTemplates/policyAssignments/DINE-VMHybridMonitoringPolicyAssignment.json
- eslzArm/managementGroupTemplates/policyAssignments/DINE-VMMonitoringPolicyAssignment.json
- eslzArm/managementGroupTemplates/policyAssignments/DINE-VMSSMonitoringPolicyAssignment.json
- eslzArm/managementGroupTemplates/policyAssignments/MODIFY-AUM-CheckUpdatesPolicyAssignment.json
Resolved an issue that prevented the policy remediation from working properly for VM Insights and Change Tracking policies. The root cause was the insufficient access granted to the Managed Identity that performs the remediation task. To solve the problem, we granted the Policy Assignments in the Landing Zone Management the permission to read the Platform Management Group.
1. Adds Role Assignments to VMInsights Policies at LZs MG granting rbacReader on Platform MG
2. Adds Role Assignments to ChangeTracking Policies at LZs MG granting rbacReader on Platform MG
3. Adds Role Assignments to Azure Update Manger Policies, granting rbacManagedIdentityOperator at the same scope as the assignment.
None
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)] …
> Fixes bug with ama role assignments

- src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Sql-Security.json
This pull request includes a change to the `src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Sql-Security.json` file. The `policyDefinitionId` for `SqlDbVulnerabilityAssessmentsDeploySqlSecurity` has been updated to include a date suffix `_20230706`, likely indicating a version update or specific configuration for this policy definition.
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#view/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FSpringstone%2FEnterprise-Scale%2FHF2%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FSpringstone%2FEnterprise-Scale%2FHF2%2FeslzArm%2Feslz-portal.json)
> Hotfix: previously updated policy not updated in initiative (low priority)

- src/Alz.Tools/functions/Alz.Tools.ps1
This fixes an issue where policy set definitions only reference one policy definition.
I tried various workarounds in the class definitions before resorting this option. It appears there is a fundamental issue in PowerShell that results in needing to fix it like this rather than in the class constructor / definition as you would expect.
N/A
N/A
This is a fix to a script library used for policy sync, so does not need portal testing.
You can see a working run based on this branch over here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/972/files
> Add policy set definition workaround
