Azure/Enterprise-Scale

docs/EnterpriseScale-Known-Issues.md
removed subscription move and reference() managementGroup resources on subscriptions.
=> Updating known issues

README.md
=> updated URIs to use uiDefinition

docs/reference/wingtip/README.md
=> updated uri to use uiDef

docs/reference/contoso/Readme.md
=> updated uri with uiDef

docs/Deploy/discover-environment.md
=> Update Dispatching commands

docs/Deploy/ES-schema.md
Really good content.
Looking forward for the full release and training material around it.
In the meantime, just providing reader feedback.
Cheers
Manu
=> just few typos

README.md, docs/Deploy/setup-github.md
=> adding info for UAA and SPN

docs/reference/wingtip/ux-foundation.json
This PR fixes a single typo on the informational mouse over icon in Azure for network connectivity ARM template deployment.
=> corrected typo

docs/EnterpriseScale-Contribution.md
=> updating contribution guide for arm-schema

.github/workflows/azops.yml
Added support for manual trigger of pull action with the new workflow_dispatch feature.
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
=> Added support for workflow_dispatch

docs/Deploy/getting-started.md
This PR adds details for enabling support for long paths on Windows
=> enable support for long paths on Windows

.github/workflows/auto-azops-pull.yml
=> Feature - Auto pull Azure Configuration

docs/reference/wingtip/README.md
=> Clarifying next step (part 1)

.github/workflows/auto-azops-pull.yml
=> Fix - Filtering Repository name for Azure/Enterprise-Scale upstream repo

.github/workflows/reference.yml
Rename automated branch to 'system'
=> Rename automated branch

.github/workflows/reference.yml
Add additional reviewers to the PR.
=> Update reference workflow

.github/workflows/azops-pull.yml, docs/Deploy/deploy-new-policy-assignment.md, docs/enterprise-scale-iab/deploy-tenant.md, docs/enterprise-scale-iab/use-git-pipeline.md, docs/reference/contoso/Readme.md
=> Doc update to refresh azopsreference folder

azopsreference/.gitignore
=> Doc - updating gitignore filter to include  Microsoft.Management and Microsoft.Subscription namespace

.github/workflows/azops-export.yml
=> Fix - azopsreference export workflow

docs/EnterpriseScale-Known-Issues.md
This PR updates the known issues for Enterprise Scale, creating a new known issue relating to errors caused by transient Management API errors.
=> Update to Known Issues

.github/workflows/azops-pull.yml
Addresses https://github.com/Azure/Enterprise-Scale/issues/97
=> Changed default pull frequency

.github/workflows/azops-export.yml, .github/workflows/azops-pull.yml, .github/workflows/azops-push.yml
=> Renaming workflow name

docs/Deploy/setup-github.md
=> Fixing code formatting

.github/workflows/azops-export.yml
Disable auto-merge on the export workflow due to branch polices on the repository.
=> Disable auto-merge

docs/reference/adventureworks/README.md
=> removal of next steps 

docs/reference/contoso/Readme.md
=> removal of next steps

README.md
=> readme refresh

README.md, docs/Deploy/deploy-new-policy-assignment.md, docs/Deploy/discover-environment.md, docs/Deploy/setup-github.md, docs/EnterpriseScale-Architecture.md, docs/EnterpriseScale-Deploy-landing-zones.md, docs/EnterpriseScale-Deploy-reference-implentations.md, docs/EnterpriseScale-Setup-azure.md
Consistency checks
Minor doc update
=> Documentation update

docs/Deploy/deploy-new-arm.md
=> fix custom ARM template policy definition name

.github/workflows/azops-export.yml, .github/workflows/azops-pull.yml, .github/workflows/azops-push.yml
=> Adding timeout to git actions

azopsreference/entScaleMgPolicyDef.json, azopsreference/entScaleSubPolicyDef.json
=> updated uri

docs/reference/wingtip/armTemplates/auxiliary/diagnosticsAndSecurity.json, docs/reference/wingtip/armTemplates/auxiliary/logAnalytics.json, docs/reference/wingtip/armTemplates/auxiliary/lz.json, docs/reference/wingtip/armTemplates/auxiliary/policies.json, docs/reference/wingtip/armTemplates/auxiliary/vwan-connectivity.json, docs/reference/wingtip/armTemplates/es-foundation.json, docs/reference/wingtip/armTemplates/portal-es-foundation.json
=> refreshing setup for es-foundation

azopsreference/entScaleMgPolicyDef.json, azopsreference/entScaleSubPolicyDef.json
=> test to bypass bug

azopsreference/entScaleMgPolicyDef.json, azopsreference/entScaleSubPolicyDef.json
=> updated deployment name

azopsreference/entScaleMgPolicyDef.json, azopsreference/entScaleSubPolicyDef.json
BugFix for Deploying Template for PolicyDefinition via portal
=> BugFix for Deploying Template for PolicyDefinition via portal

.azure-pipelines/azops-pull.yml
Fix default branch name for schedule jobs.
=> Update Azure Pipelines default branch

.azure-pipelines/azops-pull.yml, .azure-pipelines/azops-push.yml
Update the schedule trigger to ensure it always runs
Add env vars for partial Management Groups
=> Schedule Defaults & Env Vars

docs/reference/contoso/armTemplates/portal-es-vwan.json, docs/reference/wingtip/armTemplates/portal-es-add-vwan.json, docs/reference/wingtip/armTemplates/portal-es-foundation.json
- Ensuring required fields are validated in UI in addition to ARM conditions.
=> added additional ux validation

docs/reference/contoso/armTemplates/portal-es-vwan.json, docs/reference/wingtip/armTemplates/portal-es-foundation.json
* Adding subscription picker (no need to provide the sub id manually anymore)
=> UI refresh

docs/reference/adventureworks/armTemplates/portal-es-hubspoke.json, docs/reference/contoso/armTemplates/portal-es-vwan.json, docs/reference/wingtip/armTemplates/portal-es-add-vwan.json, docs/reference/wingtip/armTemplates/portal-es-foundation.json
This PR updates the Infobox Messages in ES Templates
=> ES Template Infobox Message Updates

docs/reference/adventureworks/armTemplates/auxiliary/hubspoke-connectivity.json
=> correcting parameter

docs/reference/wingtip/README.md
Fixed a typo in README for WingTips.
=> Fixed typo in README for Wingtips

docs/reference/treyresearch/README.md, docs/reference/treyresearch/armTemplates/auxiliary/hubspoke-connectivity.json, docs/reference/treyresearch/armTemplates/auxiliary/logAnalytics.json, docs/reference/treyresearch/armTemplates/auxiliary/security.json, docs/reference/treyresearch/armTemplates/es-lite.json, docs/reference/treyresearch/armTemplates/portal-es-lite.json
=> Publishing draft RI for small enterprises

docs/reference/wingtip/README.md, docs/reference/wingtip/armTemplates/portal-es-add-vwan.json
* Adding subscription picker to the vwan module for ES foundation (Wingtip)
=> adding sub picker

docs/reference/wingtip/armTemplates/portal-es-add-vwan.json
=> fixing connectivity step

docs/enterprise-scale-iab/setup-git-cicd.md
=> IAB  update for AZURE_CREDENTIALS Json

README.md
This PR rectifies a couple of minor typos and grammatical errors.
=> Rectify minor typos

docs/Deploy/ES-schema.md
=> Update tenant link

docs/reference/wingtip/armTemplates/auxiliary/logAnalyticsSolutions.json, docs/reference/wingtip/armTemplates/es-foundation.json, docs/reference/wingtip/armTemplates/portal-es-foundation.json
* Allow user to select which Azure Monitor solution to deploy
* Adding additional text and explanation to the sections.
=> enabling LA solutions

azopsreference/.gitignore
=> Update gitignore for AzOpsReference

docs/enterprise-scale-iab/setup-git-cicd.md
Fixed a typo in the link to setup-azuredevops.ms
This PR fixes a wrong link in https://github.com/Azure/Enterprise-Scale/blob/main/docs/enterprise-scale-iab/setup-git-cicd.md
=> Fixed link to setup-azuredevops.md

docs/enterprise-scale-iab/deploy-tenant.md
=> Update exercise and qualifications of process

docs/reference/adventureworks/armTemplates/portal-es-hubspoke.json
* Removal of static location list in UI definition
* Will provide available locations via API
=> adding api to pull locations

docs/reference/contoso/armTemplates/portal-es-vwan.json
* Removal of static location in UI definition
* GET request to location API to retrieve Azure regions for virtual hub.
=> adding location api

docs/reference/wingtip/README.md, docs/reference/wingtip/armTemplates/auxiliary/diagnosticsAndSecurity.json, docs/reference/wingtip/armTemplates/auxiliary/logAnalytics.json, docs/reference/wingtip/armTemplates/auxiliary/mgmtGroups.json, docs/reference/wingtip/armTemplates/auxiliary/mkPolicies.json, docs/reference/wingtip/armTemplates/es-foundation.json, docs/reference/wingtip/armTemplates/portal-es-foundation.json
* Adding support for Azure China
* Configure retention days for Log Analytics
* Deploy Azure Sentinel
* Recommendations are 'On' by default
* Enforce VM monitoring in landing zones (Windows & Linux)
* Enforce VMSS monitoring in landing zones (Windows & Linux)
* Enforce Azure Arc VM monitoring in landing zones (Windows & Linux
=> ignite-release

docs/reference/wingtip/armTemplates/es-foundation.json
=> fixing mgmt endpoint for china

docs/reference/wingtip/armTemplates/es-foundation.json
* removing '/' from management endpoint
=> removing '/' from endpoint

docs/reference/wingtip/armTemplates/auxiliary/mgmtGroups.json
=> fixing typo

docs/reference/contoso/armTemplates/auxiliary/diagnosticsAndSecurity.json, docs/reference/contoso/armTemplates/auxiliary/logAnalytics.json, docs/reference/contoso/armTemplates/auxiliary/logAnalyticsSolutions.json, docs/reference/contoso/armTemplates/auxiliary/mgmtGroups.json, docs/reference/contoso/armTemplates/auxiliary/policies.json, docs/reference/contoso/armTemplates/es-vwan.json, docs/reference/contoso/armTemplates/portal-es-vwan.json
* UX parity with foundation for platform and LZ configuration
* Added delay to workaround potential replication latency in ARM backend when deploying to a region that is paired
* Deployment optimization
* Platform recommendations are default set to On/Yes
* LZ recommendations are default set to On/Yes
=> contoso refresh

docs/reference/adventureworks/armTemplates/auxiliary/diagnosticsAndSecurity.json, docs/reference/adventureworks/armTemplates/auxiliary/logAnalytics.json, docs/reference/adventureworks/armTemplates/auxiliary/logAnalyticsSolutions.json, docs/reference/adventureworks/armTemplates/auxiliary/mgmtGroups.json, docs/reference/adventureworks/armTemplates/auxiliary/policies.json, docs/reference/adventureworks/armTemplates/es-hubspoke.json, docs/reference/adventureworks/armTemplates/portal-es-hubspoke.json, docs/reference/contoso/armTemplates/auxiliary/policies.json, docs/reference/contoso/armTemplates/es-vwan.json, docs/reference/wingtip/armTemplates/auxiliary/policies.json
* UX parity with foundation and vwan setup
* Deployment improvements
* Workaround to avoid ARM backend replication latency issue when deploying to a region that is paired
* Policy update
=> adventure works refresh

docs/reference/treyresearch/armTemplates/auxiliary/logAnalytics.json, docs/reference/treyresearch/armTemplates/auxiliary/logAnalyticsSolutions.json, docs/reference/treyresearch/armTemplates/auxiliary/mgmtGroups.json, docs/reference/treyresearch/armTemplates/es-lite.json, docs/reference/treyresearch/armTemplates/portal-es-lite.json
* Restructure of ARM templates
* UX refresh and parity with the 3 core reference implementations
* built-in policy only
=> UX refresh

docs/reference/treyresearch/armTemplates/portal-es-lite.json
=> removing outputs

docs/reference/treyresearch/armTemplates/es-lite.json
* bug in [tenantResourceId()] function
=> workaround for tenantResourceId bug

docs/reference/treyresearch/armTemplates/portal-es-lite.json
=> fixing output condition

docs/reference/wingtip/armTemplates/auxiliary/policies.json
=> adding default parameter value

README.md, docs/Deploy/setup-azuredevops.md, docs/EnterpriseScale-Known-Issues.md, docs/EnterpriseScale-Roadmap.md
* Removing [Preview] from AzOps
* Updated Known issues
* Updated readme and RI positioning
=> doc refresh

docs/Deploy/setup-azuredevops.md
Escape the quotes in the json: `"` to  `\"`   for azure devops
=> Added clarification to escape quotes

docs/reference/adventureworks/armTemplates/auxiliary/policies.json, docs/reference/contoso/armTemplates/auxiliary/policies.json
* Added default value for retentionInDays for LA policy
=> added default parameter

docs/reference/adventureworks/README.md
Updates to Adventure Works reference implementation documentation
=> AdvWorks RI doc updates

docs/reference/wingtip/armTemplates/auxiliary/diagnosticsAndSecurity.json, docs/reference/wingtip/armTemplates/auxiliary/lz.json
=> Fixing parameter value

docs/reference/wingtip/armTemplates/auxiliary/diagnosticsAndSecurity.json
=> adding logical operators to avoid reference() fail

docs/reference/wingtip/armTemplates/auxiliary/diagnosticsAndSecurity.json
=> correcting final condition

README.md
Adding support.md link on readme
=> Adding support.md link on readme

docs/enterprise-scale-iab/deploy-tenant.md
**This PR provides link to configuring Azure permissions for ARM tenant deployments. Without this link, users will struggle to implement step 3.**
=> provided link for configuring azure permissions.

docs/reference/adventureworks/armTemplates/auxiliary/diagnosticsAndSecurity.json, docs/reference/adventureworks/armTemplates/auxiliary/hubspoke-connectivity.json, docs/reference/adventureworks/armTemplates/es-hubspoke.json
* Navigating around NRP resource modeling to avoid potential race condition
* Connectivity Sub enabled for diagnostics
=> Adv patch01

docs/reference/treyresearch/armTemplates/auxiliary/hubspoke-connectivity.json
=> navigating thru NRP inconsistencies

docs/Deploy/ES-schema.md, docs/enterprise-scale-iab/use-git-pipeline.md
Update links to AzOps repo discovered in #325
=> Update template.json links in docs

.azure-pipelines/azops-push.yml, docs/Deploy/setup-azuredevops.md
This PR enables review and approval process for ADO push pipelines.
=> Update ADO pipeline and documentation

docs/reference/wingtip/armTemplates/auxiliary/hubspoke-connectivity.json
=> navigating around NRP race condition

docs/reference/contoso/Readme.md
=> Fixed Contoso AD group name typo

docs/EnterpriseScale-Deploy-landing-zones.md
* Remove [preview] from LZ creation experience
=> removing 'preview'

docs/reference/adventureworks/armTemplates/auxiliary/identity.json, docs/reference/wingtip/armTemplates/auxiliary/lz.json, docs/reference/wingtip/armTemplates/auxiliary/policies.json, docs/reference/wingtip/armTemplates/es-foundation.json
* Adding custom policy to deny RDP from internet (built-in is audit only)
=> reverting to custom policy to deny RDP

docs/reference/adventureworks/armTemplates/auxiliary/lz.json
=> policy patch

azopsreference/.gitignore
=> Update Management Group Structure

examples/policies/naming-convention/README.md
* adding readme for policydefinition example
=> adding readme

examples/landing-zones/README.md
=> adding recommendations

examples/README.md
- Readme and scope for example folder
=> Adding readme to examples

examples/README.md
=> added resourceTypes to readme

examples/landing-zones/connected-subscription/README.md, examples/landing-zones/empty-subscription/README.md, examples/landing-zones/tagged-subscription/README.md
* Correcting parameter description in subscription samples
=> Fixing param

docs/reference/adventureworks/armTemplates/auxiliary/policies.json, docs/reference/contoso/armTemplates/auxiliary/policies.json, docs/reference/wingtip/armTemplates/auxiliary/policies.json
* Correcting resource name for "Deny-ERPeering" to "Deny-VNet-Peering"
* Updated roleDefintions for Private DNS definitions
=> updating name and roleDefinitions

docs/EnterpriseScale-Roadmap.md, examples/landing-zones/subscription-into-managementGroup/README.md, examples/landing-zones/subscription-into-managementGroup/subscriptionIntoManagementGroup.json
* Updated roadmap for reference implementation(s)
* Added new sample to create new subscription and place into management group using subscription move API (/managementGroups/subscriptions)
=> added roadmap and new sample

docs/reference/adventureworks/armTemplates/auxiliary/diagnosticsAndSecurity.json
* Correcting a variable that was referenced twice in the conditional deployment
=> corrected variable reference

docs/Deploy/enable-subscription-creation.md
=> modified pre-requisites to cover azure agreement types

docs/EnterpriseScale-Deploy-landing-zones.md, examples/landing-zones/subscription-with-rbac/README.md, examples/landing-zones/subscription-with-rbac/portal-subscriptionWithRbac.json, examples/landing-zones/subscription-with-rbac/subscriptionWithRbac.json
* Added additional templates and UX for subscription provisioning (LZ with SPN RBAC)
* Added documentation
=> new lz templates

docs/EnterpriseScale-Roadmap.md
Changes spelling of "artifact" to align to form used in product for consistency
=> Aligns spelling

.azure-pipelines/azops-push.yml
PreDeployment step added to validate if deployment is required. "system" branches generated by the AzOps pull will result in skipping a deployment.
=> Push pipeline - predeployment validation

docs/reference/adventureworks/armTemplates/auxiliary/policies.json, docs/reference/contoso/armTemplates/auxiliary/policies.json, docs/reference/wingtip/armTemplates/auxiliary/policies.json
=> Update policy mode

docs/reference/adventureworks/README.md
**This PR add description about support for AZs for Adventure Works reference implementation **
=> Added support for AZs

docs/reference/adventureworks/armTemplates/portal-es-hubspoke.json
* Correcting parameter for AZFW Availability Zones
=> updating param

docs/reference/adventureworks/armTemplates/auxiliary/policies.json, docs/reference/contoso/armTemplates/auxiliary/policies.json, docs/reference/treyresearch/armTemplates/auxiliary/policies.json, docs/reference/wingtip/armTemplates/auxiliary/policies.json
This PR makes a number of updates to character cases in the policies.json file which result in incorrect re-deployments when deployed using Terraform.
=> Fix incorrect character cases

docs/EnterpriseScale-Setup-azure.md
Removed the subscription section - as this is not required to create a role assignment and looks like clutter. 
Simply retrieving $user.ID -- Based on how the user logs in to Connect-AzAccount will define who the $user is, thus no need for manual typing to get the Id.
=> fixed powershell code

docs/reference/adventureworks/README.md, docs/reference/adventureworks/armTemplates/auxiliary/azOpsArm.json, docs/reference/adventureworks/armTemplates/auxiliary/azOpsSetup.json, docs/reference/adventureworks/armTemplates/auxiliary/mgmtGroupDiagnostics.json, docs/reference/adventureworks/armTemplates/es-hubspoke.json, docs/reference/adventureworks/armTemplates/portal-es-hubspoke.json, docs/reference/contoso/armTemplates/auxiliary/azOpsArm.json, docs/reference/contoso/armTemplates/auxiliary/azOpsSetup.json, docs/reference/contoso/armTemplates/es-vwan.json, docs/reference/contoso/armTemplates/portal-es-vwan.json, docs/reference/wingtip/README.md, docs/reference/wingtip/armTemplates/auxiliary/azOpsArm.json, docs/reference/wingtip/armTemplates/auxiliary/azOpsSetup.json, docs/reference/wingtip/armTemplates/es-foundation.json, docs/reference/wingtip/armTemplates/portal-es-foundation.json
* Adding integration to Git and AzOps for CICD pipeline for the Azure platform
* UX enhancements
=> ESLZ with Git and AzOps integration

docs/reference/adventureworks/armTemplates/auxiliary/policies.json, docs/reference/contoso/armTemplates/auxiliary/policies.json, docs/reference/treyresearch/armTemplates/auxiliary/policies.json, docs/reference/wingtip/armTemplates/auxiliary/policies.json
* Updated SKU and API Version for Log Analytics & Automation
=> Update LA policy

docs/reference/adventureworks/armTemplates/auxiliary/azOpsArm.json, docs/reference/contoso/armTemplates/auxiliary/azOpsArm.json, docs/reference/wingtip/armTemplates/auxiliary/azOpsArm.json
* Avoiding RBAC replication delay by specifying principalType to SPN for UMI
=> added servicePrincipal

docs/reference/wingtip/armTemplates/auxiliary/azOpsArm.json
=> removing principalType

docs/reference/wingtip/armTemplates/auxiliary/azOpsArm.json
=> added principaltype back

docs/EnterpriseScale-FAQ.md
Adding FAQ for Subscription Picker UI
=> Adding FAQ for Subscription Picker UI

docs/reference/adventureworks/armTemplates/portal-es-hubspoke.json, docs/reference/contoso/armTemplates/portal-es-vwan.json, docs/reference/wingtip/armTemplates/portal-es-foundation.json
* Clarifying the UX for subscription requirement for GitHub integration
=> adding sub req for Git

docs/enterprise-scale-iab/use-git-pipeline.md
=> Fix broken link

docs/enterprise-scale-iab/setup-git-cicd.md
Removed the repeated "requires".
=> Fix typo: Removed the repeated "requires"

docs/reference/adventureworks/armTemplates/auxiliary/diagnosticsAndSecurity.json, docs/reference/adventureworks/armTemplates/auxiliary/logAnalytics.json, docs/reference/adventureworks/armTemplates/auxiliary/logAnalyticsSolutions.json, docs/reference/adventureworks/armTemplates/auxiliary/subscriptioSecurityConfig.json, docs/reference/adventureworks/armTemplates/es-hubspoke.json, docs/reference/adventureworks/armTemplates/portal-es-hubspoke.json, docs/reference/contoso/armTemplates/auxiliary/diagnosticsAndSecurity.json, docs/reference/contoso/armTemplates/auxiliary/logAnalytics.json, docs/reference/contoso/armTemplates/auxiliary/logAnalyticsSolutions.json, docs/reference/contoso/armTemplates/auxiliary/subscriptioSecurityConfig.json, docs/reference/contoso/armTemplates/es-vwan.json, docs/reference/contoso/armTemplates/portal-es-vwan.json, docs/reference/wingtip/armTemplates/auxiliary/diagnosticsAndSecurity.json, docs/reference/wingtip/armTemplates/auxiliary/logAnalytics.json, docs/reference/wingtip/armTemplates/auxiliary/logAnalyticsSolutions.json, docs/reference/wingtip/armTemplates/auxiliary/subscriptioSecurityConfig.json, docs/reference/wingtip/armTemplates/es-foundation.json, docs/reference/wingtip/armTemplates/portal-es-foundation.json
* Removing subscriptionId from Log Analytics workspace resource name (new name will be <eslz-prefix>-la
=> Update la name

docs/reference/adventureworks/armTemplates/es-portal.json, docs/reference/contoso/armTemplates/es-portal.json, docs/reference/wingtip/armTemplates/es-portal.json
* Moving from UI definiton to portal extension form
* Added "Enterprise-Scale Landing Zones" as title
=> Moving from UIDef to declarative extension forms

docs/reference/adventureworks/armTemplates/auxiliary/hubspoke-connectivity.json, docs/reference/adventureworks/armTemplates/auxiliary/policies.json, docs/reference/adventureworks/armTemplates/es-hubspoke.json, docs/reference/adventureworks/armTemplates/es-portal.json, docs/reference/contoso/armTemplates/auxiliary/policies.json, docs/reference/wingtip/armTemplates/auxiliary/policies.json
* Adding DINE policy for default UDR per vnet & location
* Adding support to use Azure Firewall as DNS Proxy
* Always link Azure Firewall when deployed with Azure Firewall Policy
=> ESLZ networking updates for Adventure Works

docs/reference/adventureworks/armTemplates/auxiliary/hubspoke-connectivity.json, docs/reference/adventureworks/armTemplates/es-portal.json
* Correcting SKU options for non-AZ regions for VPN and ER gateways
=> Enabling condition for non-AZ aware regions for NW

docs/reference/adventureworks/armTemplates/auxiliary/logAnalytics.json, docs/reference/contoso/armTemplates/auxiliary/logAnalytics.json, docs/reference/wingtip/armTemplates/auxiliary/logAnalytics.json
Fixing the deployment error if prefix is <= 2 char
=> Update automation account name

README.md
* Adding link to ESLZ User Guide - documentation for deployment, setup, how to use, and more
=> Adding link to ESLZ user guide

docs/reference/adventureworks/README.md
**This PR fixes:**
The link 'To learn how to create new subscriptions programmatically', as the existing URL was giving a 404 error.
=> Update README.md : Fix broken link

docs/EnterpriseScale-FAQ.md
* Adding more FAQ to the FAQ section :-)
=> FAQ Update

docs/reference/adventureworks/armTemplates/auxiliary/lz.json, docs/reference/contoso/armTemplates/auxiliary/lz.json, docs/reference/wingtip/armTemplates/auxiliary/lz.json
=> removing RA

docs/reference/adventureworks/armTemplates/auxiliary/lz.json
=> fixing resource name

docs/EnterpriseScale-FAQ.md, docs/wiki/How-Enterprise-Scale-Works.md
* Adding link from FAQ to Policy index
* Adding link from ESLZ User Guide to Policy index
=> Updated FAQ and ESLZ User Guide to reference index

docs/wiki/What-is-Enterprise-Scale.md
**This PR fixes** a minor typo in the https://github.com/Azure/Enterprise-Scale/wiki/What-is-Enterprise-Scale wiki page
=> Typo Fix in "What is ES" wiki page

.github/PULL_REQUEST_TEMPLATE.md, docs/wiki/Home.md, docs/wiki/Whats-new.md, docs/wiki/_Sidebar.md
**This PR fixes** a backlog item to create a "What's New?" page to help Enterprise Scale users to track the latest changes in a central location.
=> Create "What's New?" page for ESLZ

docs/wiki/Whats-new.md
**This PR adds** items to the "What's New?" page for June 2021
=> Update "What's New?" for June 2021

SUPPORT.md
Update support.md to include Trey Research
=> Update support.md to include Trey Research

docs/wiki/Whats-new.md
**This PR updates** the "What's New?" wiki page
=> Update Whats New

docs/wiki/Whats-new.md
**This PR updates** the wiki What's New page with the latest updates across ESLZ
=> Whats new? - Updates 17/06/2021

docs/EnterpriseScale-Known-Issues.md
I believe EastUS is paired with WestUS: https://docs.microsoft.com/en-us/azure/best-practices-availability-paired-regions
=> Paired Regions

README.md
=> Correcting url to folder

docs/reference/adventureworks/README.md, docs/reference/contoso/Readme.md, docs/reference/treyresearch/README.md, docs/reference/wingtip/README.md
**This PR fixes #638**
Upon investigation from the team this section of the table existed from a very old commit and there were actually no checks associated with this badge, so therefore it was null and void.
This PR removes the badge from all RIs.
=> Fixing issue #638

docs/wiki/Whats-new.md
**This PR fixes a formatting issue on the whats new page**
=> Formatting issue resolved

docs/EnterpriseScale-FAQ.md
=> Wrong slash

README.md
This PR adds a link to the "What's New?" page in the wiki to the repo's main README.MD
=> Add whats new to README.md

docs/wiki/Whats-new.md
**This PR updates** the "What's New?" page with the latest changes to ESLZ.
=> 13/07/2021 Whats New? - Update

docs/reference/adventureworks/README.md, docs/reference/contoso/Readme.md, docs/reference/wingtip/README.md
This PR updates the Contoso, Adventure Works and Wingtip RIs documentation to:
- provide instructions on how to deploy those RIs using the unified deployment experience.
- updates to the documents to reflect the new capabilities in the unified RI (such as private DNS zones, private link policies, or VNet in identity subscription).
=> Updates to RIs documents

eslzArm/eslzArm.json, eslzArm/managementGroupTemplates/mgmtGroupStructure/mgmtGroups.json
* Condition for NVA where Az Firewall is excluded
* scope property for management group structure
=> condition for azfw when nva is set

eslzArm/eslz-portal.json
* Renaming Enterprise-Scale Landing Zones to Azure Landing Zones
=> renaming ESLZ to ALZ

docs/wiki/Whats-new.md
**This PR updates the what's new page with the AzOps 1.3.1 release**
=> AzOps 1.3.1 Added to What's New Page

workloads/ARO/README.md
As well as the other points mentioned, ARO requires a public IP address to be created, so I've added this to the list of Azure Policy exemptions.
1. Add an entry to the "Azure Policy consideration" section to note that ARO requires a public IP
1. None
Ran through this doc with a customer today and deployment failed because of the need for a public IP address, so they needed to add an additional exemption.
=> Added ARO public IP requirement

docs/wiki/Whats-new.md
Updating whats new with the new AzOps release
=> Update Whats-new with new AzOps release

docs/wiki/Deploying-Enterprise-Scale.md
Update Az CLI Azure AD Query Output For Bash In User Guide based on feedback from #722 
1. #722 
None
=> Update Az CLI Azure AD Query Output For Bash In User Guide

workloads/ARO/README.md
When ARO is deployed in a private network certain firewall endpoint need to be whitelisted and the subnet UDR needs to be set. This PR adds those details.
Steps to deploy
None
- [ *] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [ *] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [ *] Updated relevant and associated documentation.
=> Network related details around routing and firewall for ARO in a private network.

docs/wiki/Whats-new.md
Updating the wiki "What's New?" page with the latest updates to the EA CAF docs page
1. Updating the wiki "What's New?" page with the latest updates to the EA CAF docs page
None
N/A
=> Update What's New with EA Doc Update

eslzArm/eslzArm.json
Fix Databricks policy assignments failing 
1. Fixes #804 
None
URL to test yourself: https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fjtracey93%2FEnterprise-Scale%2Ffix-data-policy-assignments%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2FeslzArm%2Feslz-portal.json
=> Fix Databricks policy assignments failing 

docs/wiki/Whats-new.md
Updated What's New with new AzOps release
https://github.com/Azure/AzOps/releases/tag/1.5.0
=> Added AzOps 1.5.0 to what's new

README.md
Fixes the "Community Call" navigation item on the main `README.md`
1. Fixes the "Community Call" navigation item on the main `README.md`
**None**
Tested and working as expected. Available to test yourself from my branch: https://github.com/jtracey93/enterprise-scale/tree/fix-nav
cc: @JefferyMitchell
=> Fix "community call" navigation item on README.md

docs/wiki/Whats-new.md
Fixes the formatting on the What's New Page to place the Updates header back to the top of the page
1. Fixes the formatting on the What's New Page to place the Updates header back to the top of the page
**None**
Is visible in the `/docs/wiki/whats-new.md` file in the branch associated to this PR.
=> Fix What's New Formatting

docs/wiki/How-Enterprise-Scale-Works.md
added space between etc and among. 
removed a superfluous "it"
This PR fixes typing mistakes in the document.
None
- [✅] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [NA] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [✔️] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [✔️] Performed testing and provided evidence.
- [NA] Updated relevant and associated documentation.
- [✖️] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)
=> added space and removed extra it

docs/wiki/Whats-new.md, eslzArm/managementGroupTemplates/policyDefinitions/policies.json
This PR is being raised to fix #864 by adding `AuditEvent` to the `Deploy-Diagnostics-AA` Policy Definition.
1. Adds `AuditEvent` to `Deploy-Diagnostics-AA` Policy Definition
n/a
Successful deployment through custom [Deploy To Azure](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Ffix-864%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Ffix-864%2FeslzArm%2Feslz-portal.json) link:
Successfully deployed Policy Definition with correct addition:
Successfully remediated Policy Assignment:
=> Add `AuditEvent` to `Deploy-Diagnostics-AA` Policy Definition

docs/wiki/Whats-new.md
Update the What's New page.
1. Add update to announce release `v1.1.0` of the `caf-enterprise-scale` Terraform module
n/a
n/a
=> Add `caf-enterprise-scale` module update to the "What's New" page

docs/wiki/FAQ.md
There are currently some broken links to heading IDs within the FAQ page. This PR fixes those links.
1. Broken links to heading IDs within the FAQ page
=> FAQ Page Fixes

docs/EnterpriseScale-Deploy-reference-implentations.md
The current wording of the "Deploy Reference Implementations" doc makes it a little tricky to read and understand. I have changed some of the wording to hopefully make it a bit of an easier read.
1. Some wording to make the document easier to read and understand
=> Update wording in Deploy Reference Implementations doc

docs/EnterpriseScale-Architecture.md
This PR fixes a link to the "Aligning Azure-native design and road maps" Design Principle and also updates the Design Area links to the new Design Area docs.
1. Fixes broken link to the "Aligning Azure-native design and road maps" Design Principle documentation
2. Changes the links to each of the 8 Design-Area documents
I have reviewed and checked each link to ensure they work as expected and point to the correct documentation.
=> Fix Design Principle and Design Area Links

eslzArm/eslzArm.json
Fix Typo 'DonNotEnforce' Causing Portal Validation Failure
1. Replaced `DonNotEnforce` with `DoNotEnforce` on line 2084 in `eslzArm.json`
2. Fixes #914 
None
URL: https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fjtracey93%2FEnterprise-Scale%2Ffix-914%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fjtracey93%2FEnterprise-Scale%2Ffix-914%2FeslzArm%2Feslz-portal.json
=> Fix Typo 'DonNotEnforce' Causing Portal Validation Failure

docs/wiki/FAQ.md, docs/wiki/Whats-new.md
This PR adds a question and answer to the FAQ around the `AzureDiagnostics` table in Log Analytics Workspaces for very large deployments.
1. Add question and answer to the FAQ for the `AzureDiagnostics` table
2. Updated "What's new?" page also
None
Displays correctly in branch here: https://github.com/jtracey93/Enterprise-Scale/blob/diagnostics-table-faq-add/docs/wiki/FAQ.md
=> Add FAQ Q&A for Diagnostic Table

docs/wiki/Whats-new.md
Whats New Updates - 21/04/2022
1. Added new CAF docs to whats new wiki page
None
Display correctly in fork/branch
=> Whats New Updates - 21/04/2022

docs/wiki/Whats-new.md
Update What's New for ALZ TF v2.0.0
1. Update What's New for ALZ TF v2.0.0
None
Displays correctly in fork/branch
=> Update What's New for ALZ TF v2.0.0

eslzArm/managementGroupTemplates/policyDefinitions/china/mcPolicies.json, eslzArm/managementGroupTemplates/policyDefinitions/gov/fairfaxPolicies.json, eslzArm/managementGroupTemplates/policyDefinitions/policies.json
Correct typo
- fixes #969 
n/a by inspection
=> Correct typo in displayName of Deny-Storage-minTLS policy

docs/wiki/Whats-new.md
Add link to new version of ALZ TF module
1. Add link to v2.0.2 of TF module
n/a by inspection
=> Update what's new with ALZ TF module v2.0.2

docs/wiki/Whats-new.md
Add latest ALZ TF module updates to the what's new page
n/a
n/a
n/a
=> Add latest ALZ TF module updates

docs/Deploy/es-schema.md
Discovered Tenant Root scope isn’t required for subscription placement, just MG and Subscription scopes are needed.
Updates the documentation concerning the Permission Scope needed for each piece of the ESLZ deployment. Changing Subscription Placement step to reflect that it doesn’t require Root Tenant scope. 
1. Changes scope required for Subscription Placement
1. None
Successfully ran the equivalent template from the LZ-Bicep repo using a service principal that does not have Tenant Root scope assigned. Only needed Owner at the MG and Subscription.  
The below URLs can be updated where the placeholders are, look for `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}` & `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}`, to allow you to test your portal deployment …
=> Updating Scope requirement for Subscription Placement

eslzArm/eslz-portal.json, eslzArm/eslzArm.json
Fixes a small bug introduced in PR #1022 that meant the DDoS Plan deployment failed and therefore resulting Private DNS Zones and associated RG failed, due to dependency logic.
1. Removes unrequired `location` property from DDoS Plan deployment
None
Testing can be done via DTA button below. Evidence:
**Before**
**After**
[![Deploy To Azure](https://docs.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/Cust …
=> Investigate deployment issues

.github/workflows/code-review.yml, .github/workflows/test-portal.yml
Update the PR trigger to `pull_request_target` to enable access to secrets when raised from a fork.
Remove push trigger for super linter
_See description above_
n/a
_to follow_
n/a
=> Update trigger to `pull_request_target`

eslzArm/eslzArm.json
Remove unrequired `location` for RG deployments
1. Remove unrequired `location` for RG deployments
2. Fixes #1041 
3. Fixes #1040 
None
Validation also passes now for AzOps when enabled.
[![Deploy To Azure](https://docs.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Ffix-alz-portal-bugs%2FeslzArm%2FeslzArm.json/ …
=> Remove unrequired `location` for RG deployments

.github/workflows/update-portal.yml
Refactor `Update Portal Experience` workflow to support forks
1. Fixes error when workflow triggered from PR
n/a
Please review GitHub Actions
=> Refactor `Update Portal Experience` workflow to support forks

.github/actions-config/gh-ado-sync-config.json, .github/workflows/gh-ado-sync.yml
[![Deploy To Azure](https://docs.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBla …
=> add gh to ado sync config

.github/actions-config/gh-ado-sync-config.json, .github/workflows/gh-ado-sync.yml, eslzArm/eslzArm.json
AzOps Deployment Fixes & Enable GitHub to ADO Sync
1. #1044 
2. Enable GitHub to ADO Sync
None
[![Deploy To Azure](https://docs.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Ffix-azops%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Ffix-azops%2Fe …
=> AzOps Deployment Fixes & Enable GitHub to ADO Sync

.github/workflows/gh-ado-sync.yml, eslzArm/managementGroupTemplates/policyDefinitions/policies.json
Fix GH to ADO Sync Bugs. Convert to 1 way sync (GH to ADO only)
1. Fix GH to ADO Sync Bugs. Convert to 1 way sync (GH to ADO only)
None
Working in ALZ-Bicep repo and ADO - https://github.com/Azure/ALZ-Bicep/actions/workflows/gh-ado-sync.yml
=> Fix GH to ADO Sync Bugs

src/Alz.Tools/Alz.Classes/Alz.Classes.psm1, src/Alz.Tools/Alz.Enums/Alz.Enums.psm1, src/Alz.Tools/functions/Alz.Tools.ps1
Updates the `Alz.Tools` PowerShell module to provide support for converting resource templates to format needed for the Bicep repository.
1. Add Bicep support to `Alz.Tools`
n/a
Please see output of https://github.com/JamJarchitect/ALZ-Bicep/pull/10/files
=> Add Bicep support to `Alz.Tools`

docs/wiki/Whats-new.md
Add lines around diagnostics settings policies update.
1. Update to Whats New only.
N/A
N/A 
N/A
- [x ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)
=> Update what's new for October 2022

README.md, docs/wiki/ALZ-Policies.md, docs/wiki/Home.md, docs/wiki/_Sidebar.md
Wiki Updates for broken images and nav link
1. Wiki image fix
2. Navigation link on home page
1. N/A
[![Deploy To Azure](https://docs.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FJamJarchitect%2FEnterprise-Scale%2Fwikiupdatesjj%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FJamJarchitect%2FEnterprise-Scale%2Fwikiupdatesjj%2FeslzArm%2Feslz-portal.json)
[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazuregov.svg?sanitize=true)](https://portal.azure.us/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fr …
=> images and nav

docs/wiki/Whats-new.md, eslzArm/eslz-portal.json
Update Available AZs in Portal Experience 
1. Fixes #1114 
None
[![Deploy To Azure](https://docs.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fazure%2FEnterprise-Scale%2Ffix-114%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fazure%2FEnterprise-Scale%2Ffix-114%2FeslzArm%2Feslz-portal.json)
=> Update Available AZs in Portal Experience 

docs/wiki/ALZ-Policies.md
Link to see complete list of built-in and custom policies on line 19 in the markdown points off to an old page which then references this page again.
Updated anchor in link to move user to correct section on this page.
1. Fixes link on Line 19 with correct target.
None
N/A
=> Correcting link pointing to old location.

docs/wiki/Whats-new.md, eslzArm/managementGroupTemplates/policyDefinitions/policies.json
What is new wiki update
information to what's new on changes happened based on #1120  and #1132 
no breaking change
screenshot
=> Wiki update

docs/wiki/ALZ-Deprecated-Services.md, docs/wiki/Whats-new.md
Task [AB#26221](https://dev.azure.com/CSUSolEng/Azure%20Landing%20Zones/_workitems/edit/26221?src=WorkItemMention&src-action=artifact_link)
1. *Added a link for  (https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/Migrate-ALZ-Policies-to-Built%E2%80%90in.md) to ([Enterprise-Scale/ALZ-Deprecated-Services.md at main · Azure/Enterprise-Scale (github.com)](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Deprecated-Services#azure-landing-zones-deprecated-services) page*
2. *Fixed the broken Links in (https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) section : November 2022 for (https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Deprecated-Services#azure-landing-zones-deprecated-services) …
=> updating docs

docs/reference/adventureworks/README.md
Update link to image after it was moved to fix #1204 
1. Fix #1204 
None
Just docs, linting will suffice
=> Fix #1204 Image Link Broken

.github/fabricbot.json
Add rule to fabricbot to ask Jeff to review if portal change on main
1. Add rule to fabricbot to ask Jeff to review if portal change on main
None
Linting will suffice. Config created via FabricBot config tool
=> Add rule to ask Jeff to review if portal change on main

.github/workflows/test-portal.yml
As per request of upstream issue on GitHub runners with Az PowerShell module: https://github.com/actions/runner-images/issues/7034#issuecomment-1443820736
1. Hopefully #1199 - but must merge to be able to test 
N/A
Not possible before being merged, but destroy step not working anyway as per #1199 so no risk.
=> Pin to Az PowerShell Module Version 9.4.0 for #1199

docs/wiki/Whats-new.md
Moving new contribution What's New policy content in line with other updates.
1. N/A
1. N/A
N/A
N/A
=> Policy refresh wiki minor update

.github/workflows/update-portal.yml, docs/wiki/FAQ.md, docs/wiki/Whats-new.md, eslzArm/managementGroupTemplates/policyDefinitions/policies.json, eslzArm/managementGroupTemplates/roleDefinitions/customRoleDefinitions.json
Add New FAQ Q&A for AMA Migration Topic
1. Closes [AB#25746](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/25746)
2. Amend `Update Portal` Workflow to trigger only when required
None, just docs
Linting will suffice as just docs.
=> Add New FAQ Q&A for AMA Migration Topic

docs/reference/Readme.md
Spelling correction of Susbcription to Subscription
Spelling correction of Susbcription to Subscription
=> Spelling correction of Susbcription

.github/fabricbot.json
Update FabricBot Config for Jeff Portal Review Action
1. Update FabricBot Config for Jeff Portal Review Action
None
Linting will suffice
=> Update FabricBot Config for Jeff Portal Review Action

docs/wiki/Deploying-ALZ-ZTNetwork.md
Adding some things for feedback, we can discuss their inclusion.
For the Hub and Spoke / VWAN - I phrased it as hub/spoke as the primary topology.  This way if there is a question about vwan we can say that vwan uses the same topology mechanics, and let it proceed from there.
Added language about the NSGs not having the explicit allows.
The below URLs can be updated where the placeholders are, look for `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}` & `{YOUR GITHUB BRANCH …
=> Update on items

docs/wiki/Whats-new.md
Updating March 2023 What's New section to remove unnecessary breaking changes as confirmed.
1. Update `Whats-new.md`
1. N/A
=> What's New update ONLY

eslzArm/eslz-portal.json
Minor Portal Accelerator UI Update - updating infoblock text for online management groups.
1. Update `eslz-portal.json`
1. N/A
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#view/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FSpringstone%2FEnterprise-Scale%2Fpolicy-refresh-portalupdate%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FSpringstone%2FEnterprise-Scale%2Fpolicy-refresh-portalupdate%2FeslzArm%2Feslz-portal.json)
=> Policy-Refresh: Minor Portal Accelerator UI Update

docs/wiki/Whats-new.md
Updating date for What's New content
1. Whats-new.md updated
1. N/A
N/A
N/A
=> Policy-Refresh: Updating date for What's New content

SUPPORT.md
Spelling of corelation to correlation
1. Spelling of correlation
=> Spelling of correlation

docs/reference/wingtip/README.md
1. Spelling correction of pre-requisites
=> Spelling correction of pre-requisites

docs/wiki/ALZ-Deprecated-Services.md, docs/wiki/Whats-new.md, eslzArm/eslz-portal.json, eslzArm/eslzArm.json, eslzArm/eslzArm.test.param.json, eslzArm/fairfaxeslz-portal.json, eslzArm/subscriptionTemplates/logAnalyticsSolutions.json
Removed Service Map from the ALZ accelerators, templates paramater files.
1. Removed Service Map as per User Story 27443
1. None
Removed from portal accelerators
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Farjenhuitema%2FEnterprise-Scale%2Fmain%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Farjenhuitema%2FEnterprise-Scale%2Fmain%2FeslzArm%2Feslz-portal.json)
[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazuregov.svg?sanitize=true)](https://portal.azure.us/#blade/Microsoft_Azure_CreateUIDef …
=> Removed Service Map

docs/wiki/ALZ-Policies.md, docs/wiki/Whats-new.md
Small wiki update fixing URLs pointing to the new Policies FAQ.
1. Updated ALZ-Policies and Whats-new URL links to be wiki friendly.
1. N/A
N/A
N/A
=> Fixing wiki URLs

docs/wiki/Migrate-ALZ-Policies-to-Built‐in.md
Spelling Correction: Intiative = initiative
=> Spelling correction

docs/wiki/_Sidebar.md
Updates wiki sidebar to correspond to content on creating landing zones.
1. Update _Sidebar.md to collapse "Create subscriptions / landing zones" into one section only
None
Documentation only
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR GITHUB ORG/ACCOUNT HERE - Remove Curly Brackets …
=> Update sidebar to correspond to content

docs/wiki/Whats-new.md, eslzArm/eslz-portal.json
Fix #1370 - Remove DNS Proxy Option When AZ FW == Basic
1. Fix #1370
None
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Ffix-dns-proxy-basic%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Ffix-dns-proxy-basic%2FeslzArm%2Feslz-portal.json)
=> Fix #1370 - Remove DNS Proxy Option When AZ FW == Basic

.github/workflows/unit-test-policies.yml
Change to Ubuntu Runner - Policy Unit Tests
1. Change to Ubuntu Runner - Policy Unit Tests
None
=> Change to Ubuntu Runner - Policy Unit Tests

.github/actions-pester/PolicyPesterTestHelper.psm1, .github/actions-pester/Test-ModifiedPolicies.Tests.ps1
This fixes the unit tests with paths being incorrect.
For example: https://github.com/Azure/Enterprise-Scale/actions/runs/5484091317/jobs/9991181836?pr=1369
1. This issue fixed the output of the function and the issue with the paths getting merged.
1. This is a bug fix.
https://github.com/oZakari/Enterprise-Scale/actions/runs/5489904858/jobs/10004656236?pr=22
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2F{YO …
=> Bug: Fixed function results to not return string for Unit Tests

.github/actions-pester/Test-ModifiedPolicies.Tests.ps1
Enhance pester outputs
1. Enhance pester outputs
None
=> Enhance pester outputs

.github/workflows/test-portal.yml, .github/workflows/unit-test-policies.yml, .github/workflows/update-portal.yml
Enhance security on privileged workflows
1. Change one test that doesn't need `pull_request_target` to just use `pull_request`
2. Change workflows that need to use `pull_request_target` to have additional label protection
None
The label protection technique is used successfully here https://github.com/Azure/terraform-azurerm-lz-vending
=> Enhance security on privileged workflows

docs/wiki/Whats-new.md, eslzArm/subscriptionTemplates/logAnalyticsSolutions.json
Update to Sentinel simplified pricing tiers as per: https://learn.microsoft.com/en-us/azure/sentinel/enroll-simplified-pricing-tier?tabs=azure-resource-manager
1. Update to Sentinel simplified pricing tiers as per: https://learn.microsoft.com/en-us/azure/sentinel/enroll-simplified-pricing-tier?tabs=azure-resource-manager
None
Tests will suffice
=> Update to Sentinel simplified pricing tiers

.github/workflows/test-portal.yml
Workflow PS version update.
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR …
=> Update workflow to 10.1

eslzArm/eslzArm.json
Fixes deployment uniqueness for mg diag settings, which causes an error for TF policy sync process.
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR GITHUB …
=> fix: make mg diag settings deployment name unique

.github/actions-pester/PolicyPesterTestHelper.psm1, .github/workflows/code-review.yml
Add base ref for policy unit tests
1. Add base ref for policy unit tests
None
=> Add base ref for policy unit tests

eslzArm/eslzArm.json
Updates AMBA to the latest release: 2023-10-06
1. Updates AMBA to the latest release: 2023-10-06
N/A
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR GITHUB ORG/ACCOUNT HERE - Remove Curly Brackets Also}%2FEnterprise-Scale%2F{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets …
=> Update AMBA version 2023-10-06

eslzArm/eslzArm.terraform-sync.param.json, eslzArm/managementGroupTemplates/policyDefinitions/policies.json, eslzArm/managementGroupTemplates/roleDefinitions/customRoleDefinitions.json
Update eslzArm.terraform-sync.param.json for TF policy assignment sync fix
1. Update eslzArm.terraform-sync.param.json for TF policy assignment sync fix
None
Linting will suffice
=> Update eslzArm.terraform-sync.param.json for TF policy assignment sync fix

docs/wiki/FAQ.md
Doc Updates - clarification on guidance for services that may not deploy in ALZ.
[AB#30974](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/30974)
=> FAQ Guidance for Services that won't deploy in ALZ

eslzArm/eslzArm.json
Updates AMBA to the latest release: 2023-11-14
1. Updates AMBA to the latest release: 2023-11-14
N/A
Deployment:
Version:
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Farjenhuitema%2FEnterprise-Scale%2Fmain%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Farjenhuitema%2FEnterprise-Scale%2Fmain%2FeslzArm%2Feslz-portal.json)
=> Update AMBA version 2023-11-14

docs/reference/treyresearch/README.md
Added note that references the use of managed identities.
Discussed the creation of the PR in this issue: https://github.com/Azure/Enterprise-Scale/issues/1473#issuecomment-1812153885
> Please also replace the curly brackets on the …
=> Update README.md to reference the use of managed identities.

docs/wiki/Community-Calls.md
=> Fix Slide Link

docs/wiki/ALZ-Policies-FAQ.md, docs/wiki/Whats-new.md
Updated Policy FAQ in the wiki to include guidance for identified services that can cause issues if not fully configured.
=> Wiki FAQ Update - Private DNS Zone / Privatelink Guidance

docs/wiki/Deploying-ALZ-ZTNetwork.md, docs/wiki/Whats-new.md
Updated broken links to the Zero Trust Guidance Center in the ALZ Zero Trust Networking guidance.
1. Broken links in the Zero Trust Guide, as mentioned in #1519 
1. None
Tested links from private repo and resolved correctly.
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR GITHUB ORG/ACCOUNT HERE - …
=> Fixed broken links in Zero Trust page

.github/workflows/test-portal.yml
Fix for the GHA workflow that test portal deployments.
=> Fix for GHA testing workflow

docs/wiki/Whats-new.md, eslzArm/eslzArm.json, eslzArm/managementGroupTemplates/policyAssignments/DINE-UserAssignedIdentityVMInsightsAssignment.json
Changed enforcementMode of the assignment of Policy "Deploy-UserAssignedManagedIdentity-VMInsights" to Default to ensure automatic creations of resources for new subscriptions.
1. Changed enforcementMode of Policy "Deploy-UserAssignedManagedIdentity-VMInsights" to Default
None
Deployment
Before
After
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fpatch-uamipolicy%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fpatch-uamipolicy%2FeslzArm%2Feslz-portal.json)
[![Deploy To …
=> Update enforcement mode for Policy "Deploy-UserAssignedManagedIdentity-VMInsights"

eslzArm/managementGroupTemplates/policyAssignments/MODIFY-AUM-CheckUpdatesPolicyAssignment.json
Incorrect casing of resource type causes issues in Terraform.
@jtracey93 @Springstone 
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR GITHUB ORG/ACCOUNT …
=> fix: resource case error

docs/wiki/Deploying-ALZ-CustomerUsage.md, docs/wiki/Whats-new.md, eslzArm/eslzArm.json, eslzArm/managementGroupTemplates/policyDefinitions/policies.json, eslzArm/managementGroupTemplates/roleDefinitions/customRoleDefinitions.json
This pull request primarily introduces updates to the telemetry system of the Azure Landing Zones (ALZ) Accelerator project, along with updates to the project documentation. The main changes include the addition of new unique identifiers (PIDs) for different deployment scenarios, updates to the deployment script `eslzArm.json` to handle these new PIDs, and updates to the project's documentation to reflect these changes.
Documentation updates:
* [`docs/wiki/Deploying-ALZ-CustomerUsage.md`](diffhunk://#diff-1345bfe8513c475ea5a5f1bd9b9e970fde5d646b62b4ca9e9c71b70fca05a406R29-R33): Added new PIDs for various ALZ Accelerator/ESLZ ARM Deployment scenarios, including single platform subscription, multiple platform subscriptions, and different networking configurations.
* …
=> feat: Add additional, optional, telemetry for ALZ team to identify deployment styles of ALZ

README.md
This pull request includes a minor yet significant addition to the `README.md` file. The change introduces a new section titled "Azure Landing Zones Roadmap", which provides information about the ongoing evolution of the Azure Landing Zones (Enterprise-Scale) architecture and a link to the roadmap. This addition will help users understand the future plans for the architecture and how it will continue to evolve.
=> Add Azure Landing Zones Roadmap to README.md

eslzArm/managementGroupTemplates/policyAssignments/DENY-DINE-APPEND-TLS-SSL-PolicyAssignment.json, eslzArm/managementGroupTemplates/policyAssignments/DINE-MDFCConfigPolicyAssignment.json
This pull request includes changes to two JSON files in the `eslzArm/managementGroupTemplates/policyAssignments` directory. The changes involve updating the names of certain policy assignments. 
Changes:
* [`eslzArm/managementGroupTemplates/policyAssignments/DENY-DINE-APPEND-TLS-SSL-PolicyAssignment.json`](diffhunk://#diff-8d359919c8d0b0122d761dbe37f5b58fe560dca9373b1d661478292ae20c01adL29-R29): The name of the `deployEncryptionInTransit` policy assignment was updated from `Enforce-TLS-SSL` to `Enforce-TLS-SSL2`.
* [`eslzArm/managementGroupTemplates/policyAssignments/DINE-MDFCConfigPolicyAssignment.json`](diffhunk://#diff-674e885ca90b87d3e763d5a15c532f4a4dc3c914878729c3dc037c3e760a9de1L137-R137): The name of the `azureSecurity` policy assignment was updated from `Deploy-MDFC-Config` to …
=> Hotfix: Minor assignment HotFix to address repeated deployment conflict

docs/wiki/Whats-new.md
This pull request includes changes to the `docs/wiki/Whats-new.md` file. The changes update the "This release includes:" section with a special note about changes in "assigned by default" initiative assignments. The new assignments are provided in a table format for clarity.
The most important change is:
* [`docs/wiki/Whats-new.md`](diffhunk://#diff-dc6403d6507d3ee6a1e907f047aa79fc3a0733256a2fdf5507a64ac754e7ff61R122-R128): Added a special note about changes in "assigned by default" initiative assignments. The note includes a table that lists the initiative, display name, original assignment name, and new assignment name.
=> Adding note to remove default assignments.

eslzArm/eslz-portal.json
Fix typo in portal experiance.
1. Fix tiny typo in portal experiance
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR GITHUB ORG/ACCOUNT HERE - Remove Curly …
=> Fix tiny typo

.github/workflows/scorecard.yml, README.md
This PR adds the OpenSSF scorecard and associated badge.
N/A
N/A
N/A
=> Add OpenSSF Scorecard
